### ISSUE TITLE
onSeek

### ISSUE THREAD

**Issue by santosh279** [micnews/react-jw-player#102]
Does the react -jwp-player support the onSeek() functionality?

**Comment by ellell** [comment]
@santosh279 Yes, you should be able to hookup all events available in the jwplayer sdk, see https://github.com/micnews/react-jw-player#event-hooks So passing in prop `onSeek` for this should work. 

Closing this out, feel free to reopen if you're having issues with it.

**Comment by gvillo** [comment]
Hi!, I am not able to use onSeek, I've forked and pushed a fix for this, it's missing onSeek prop on libraary
