### ISSUE TITLE
Feature Request: Add onDisplayClick prop

### ISSUE THREAD

**Issue by ryanwalters** [micnews/react-jw-player#106]
It would be great to have access to the [`displayClick`](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayerondisplayclick) event.

In my case, I have a player instance within an overlay with its own controls (media gallery). When interacting with the player, I need to hide the overlay's controls. `onPlay` and `onPause` get me part of the way, but on mobile devices, tapping on the display does not automatically pause the video.

Note: I have tried passing `onDisplayClick` into the component as part of the [dynamic event hook support](https://github.com/micnews/react-jw-player#event-hooks), but nothing seems to happen.

**Comment by danmakenoise** [comment]
@ryanwalters sorry for the delay in responding! I don't see a `displayClick` event anywhere in the JW Player docs, can you link us to what you are seeing?

**Comment by ryanwalters** [comment]
https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayerondisplayclick

**Comment by danmakenoise** [comment]
@ryanwalters on first glance: `onDisplayClick` prop definitely works on our end. It may be a bug with JWPlayer itself if it's not firing on mobile properly. Can you pop in a code snippet of how you are using it here so I can double-confirm that this isn't an issue on our end for you?

**Comment by ryanwalters** [comment]
I can confirm that this is just an issue in my implementation, sorry for the false alarm!
