### ISSUE TITLE
Player works but I keep getting GET Errors

### ISSUE THREAD

**Issue by JacobMJones** [micnews/react-jw-player#107]
Here is how I setup the player: https://pastebin.com/yWzAJAcz

Every second or so I get this error, or some variation thereof:

GET http://jwpltx.com/v1/jwplayer6/ping.gif?h=-1318621449&e=t&n=4698044703103532&aid=MpPDdOMrEeeyfgpVuA4vVw&at=1&c=-1&ccp=0&cp=1&d=1&eb=1&ed=9&emi=10l11r21t8nq&i=0&id=sBznUpBA&lid=gd6qv613bv3e&lsa=read&mt=1&pbd=1&pbr=1&pgi=28wzr117qeqr&ph=1&pid=YAoKxdyN&pii=0&pl=339&plc=1&pli=18gc3lidwv9t&pp=html5&prc=2&ps=3&pss=1&pt=React%20App&pu=http%3A%2F%2Flocalhost%3A3000%2F&pv=8.4.6&pyc=1&s=0&sdk=0&stc=2&tv=3.3.0&tvs=0&vb=0&vi=0&vl=28&wd=641&abm=0&mu=http%3A%2F%2Fcontent.jwplatform.com%2Fvideos%2FsBznUpBA-EGp6QPLm.mp4&pw=48&q=8&ti=11&vh=720&vw=1280&ubi=0&sa=1535381770288 0 ()

**Comment by ellell** [comment]
@JacobMJones couldn't access that hastebin, but it sounds like an error coming from the [jwplayer library](https://github.com/jwplayer/jwplayer/issues) as this react wrapper does not perform any requests itself.

**Comment by JacobMJones** [comment]
Sorry I just noticed the link isnt working.
https://pastebin.com/yWzAJAcz

That should work. Thanks for the quick response. Ya I figured it was on their side but since I am using your library, they don't seem willing to help.

**Comment by JacobMJones** [comment]
I appears to only be happening on my computer
