### ISSUE TITLE
Would you allow us to link this in the JW repo readme?

### ISSUE THREAD

**Issue by johnBartos** [micnews/react-jw-player#109]
First, great job on this project. A lot of people (and recently more) want to use JW and React together. If they ask nicely we usually direct them to this repo but it's always been ad hoc. However, we'd think it'd be great to officially say that this is the best way to integrate the two. Would the maintainers of this project be OK with us linking this repo in our readme?

**Comment by ellell** [comment]
@johnBartos Thanks! Definitely, we'd be happy to be linked to in the readme!

**Comment by danmakenoise** [comment]
@johnBartos just confirming with you we can close this issue since it looks like you guys are about to merge this on your end?

**Comment by johnBartos** [comment]
Yeah of course!
