### ISSUE TITLE
Make ReactJwPlayer usable inside a web component

### ISSUE THREAD

**Issue by cavez86** [micnews/react-jw-player#110]
At the moment is not possible to use this component inside a web component because jwplayer can't find the DOM element with the specified id inside the ShadowRoot.
A possible solution for this is to initialize jwplayer passing the DOM element instead of the id (it works).

**Comment by cavez86** [comment]
@ellell done -> https://github.com/micnews/react-jw-player/pull/111 ;)

**Comment by ellell** [comment]
Fixed by https://github.com/micnews/react-jw-player/pull/111
