### ISSUE TITLE
Flash player displayed instead HTML5 video player

### ISSUE THREAD

**Issue by fedojo** [micnews/react-jw-player#114]
Hi!

Is there a way to block displaying flash player? When Flash player is installed video from JW player is displaying Flash object and doesn't load proper media. Is there any option to disable this behaviour?

Thanks in advance for response

**Comment by danmakenoise** [comment]
@fedojo This is usually an issue with JW Player itself. What version are you using, and what browser?

**Comment by fedojo** [comment]
Firefox: 63.0.3
react-jw-player: 1.16.0
jw-player: 7.12.13

**Comment by danmakenoise** [comment]
@fedojo since you are using JW7, check [here](https://developer.jwplayer.com/jw-player/docs/developer-guide/jw7/configuration-reference/). You should be able to use the `primary` setup option, set to `html5` to override this. You can pass this in via `customProps`.

```
<ReactJWPlayer
  customProps={{
    primary: 'html5',
  }}
/>```

**Comment by fedojo** [comment]
Thanks @danmakenoise ! 

We changed config on our side and moved to version 8 of JWPlayer. It resolved an issue on our side.
I hope your code will save someone's life ! :)
