### ISSUE TITLE
load a new json feed

### ISSUE THREAD

**Issue by scottmont** [micnews/react-jw-player#12]
how would you load a new json and restart the player ?

**Comment by danmakenoise** [comment]
There would be two ways to do this:

1.) Using React, you can unmount the component manually, and render a new instance with the new JSON object.

2.) Once the player is rendered, you can tap in to the traditional JW Player SDK to load new files.

Let me know if you need help with either of those! Or, if you have a suggestion for how we could do this better, let me know that too!
