### ISSUE TITLE
Playlist List Question (Not an issue really)

### ISSUE THREAD

**Issue by rocco-solsys** [micnews/react-jw-player#121]
I'm trying to get a playlist "list" to actually show up under my Video is there a way to do that with this component?

Can't seem to attache a screenshot of what I am talking about.You can see an example here:
https://wmfd.com/watch-WMFD-TV-Shows/i-love-my-job/index.asp

**Comment by danmakenoise** [comment]
@rocco-solsys you would need to build that out separately from ReactJWPlayer. This component would only be the video player itself! Closing this, if that's okay.

You would be able to change props on this component to accomplish that behavior, though!
