### ISSUE TITLE
Check for valid player instance before calling initialize

### ISSUE THREAD

**Issue by esetnik** [micnews/react-jw-player#137]
https://github.com/micnews/react-jw-player/blob/master/src/react-jw-player.jsx#L87

I receive many errors like:

```
TypeError: n.setup is not a function
```

Traced it to ../node_modules/react-jw-player/dist/helpers/initialize.js in default at line 26:1
The player instance is not guaranteed to be still available on the page at the time that initialize is called. We need to check to see if it is null since it may have been destroyed.

**Comment by diogo-codengage** [comment]
when will it be published?

**Comment by ubialimv** [comment]
Any news about this issue?
