### ISSUE TITLE
Continue Playing Video

### ISSUE THREAD

**Issue by soumojit-technoexponent** [micnews/react-jw-player#185]
I want continue play a video where I previously stopped. I got the seekRange value using onTIme event. How to update the Starting point. 
Please help me asap I'm trying to fix it for last 2 days.

**Comment by jvjijith** [comment]
@soumojit-technoexponent Hi did you get any solution . I'm also stuck with the same issue

**Comment by soumojit-technoexponent** [comment]
No, I didn't get any solution. 
For now you can try video-react package, there is a inbuilt event called startTime.
