### ISSUE TITLE
onExitFullScreen firing as soon as onEnterFullScreen has fired

### ISSUE THREAD

**Issue by joemitchard** [micnews/react-jw-player#19]
Hi guys,

When I click the players' full-screen button, it appears to flash up and then exit full screen again. After a little investigation, it appears that the onExitFullScreen event is being thrown as soon as it enters full screen. 

Double clicking the video toggles full screen without an issue. So I suspect there's something up with the button.

Any help with this would be much appreciated!

Here's my current implementation:

```
import * as React from 'react';
import * as propTypes from 'prop-types';
import ReactJWPlayer from 'react-jw-player';
import LoaderComponent from '../../../shared/loader/loader.component';
import AlertComponent from '../../../shared/alert/alert';

class VideoBlockComponent extends React.Component<any, any> {

    constructor(props: any) {
        super(props)

        this.playerUrl = `url(/client/vendor/jw-player/jwplayer.js)`;
        this.defaultWidth = '100%';
        this.defaultAspectRatio = '16:9';

        this.onEnterFullScreen = this.onEnterFullScreen.bind(this);
        this.onExitFullScreen = this.onExitFullScreen.bind(this);        
    };
    
    playerUrl: string;
    defaultWidth: string;
    defaultAspectRatio: string;

    componentDidMount() {
        this.props.fetchContent();
    };

    onEnterFullScreen(event: any) {
        console.log(event);
    };

    onExitFullScreen(event: any) {
        console.log(event);
    };

    render() {
        return (
            <div className="container video-block loader-wrapper">
                {this.props.video &&
                    <ReactJWPlayer
                        playerId={this.props.id}
                        playerScript={this.playerUrl}
                        file={this.props.video.videoUrl}
                        image={this.props.video.imageUrl}
                        isAutoPlay={this.props.video.autoPlay}
                        onEnterFullScreen={this.onEnterFullScreen}
                        onExitFullScreen={this.onExitFullScreen}
                        aspectRatio={ this.defaultAspectRatio }
                        customProps={ { width:this.defaultWidth } }
                    />
                }
                <LoaderComponent isActive={this.props.loading} isOverlay={true} />
                {this.props.errorMessage &&
                    <AlertComponent message="Fetching data error. Please try again!" type="error" />
                }
            </div>
        );
    }
}

export default VideoBlockComponent;
```

**Comment by danmakenoise** [comment]
@joemitchard I can't reproduce this on my end, so I suspect there is something different about the version of the player you are using. What version of JW Player do you have running in your hosted script at: `/client/vendor/jw-player/jwplayer.js`?

**Comment by joemitchard** [comment]
Hi @danmakenoise, thanks for getting back to me!

Sure, it is currently 7.11.2

**Comment by joemitchard** [comment]
Hi @danmakenoise , did you ever get round to looking into this?

**Comment by danmakenoise** [comment]
@joemitchard I tried to recreate it on our end, and couldn't do it. Any chance you could get a sample page up and running?

**Comment by joemitchard** [comment]
@danmakenoise no worries, I'll see what I can do over the weekend.

**Comment by joemitchard** [comment]
@danmakenoise sorry for not getting back sooner, I actually removed your plugin from the equation and implemented a wrapper manually... the same issue, this isn't an issue with your plugin but jwplayer itself, I'll close the issue

**Comment by danmakenoise** [comment]
@joemitchard good to know, thanks for following up!

**Comment by m2jobe** [comment]
Facing this same issue but cant find anything from jw player docs

**Comment by joemitchard** [comment]
@m2jobe it turned out that it was the ID we were passing into the player, we were passing Page ID (an integer). JW Player requires that page ID is a string value. Passing in ``jw-player-${this.props.id}`` solved the issue.
