### ISSUE TITLE
exposing jwplayer object

### ISSUE THREAD

**Issue by tariqinaam** [micnews/react-jw-player#20]
I am using your module in my react app. and try to use jwplayer.on('time')  or jwplayer().getPosition() but they are not available. 
Is it possible to expose whole jwplayer object/event.

**Comment by danmakenoise** [comment]
You can access the object directly via the jwplayer sdk itself. Whatever id you pass in as `playerId` can be used to reference the player. So, if I have:

```javascript
<ReactJWPlayer playerId='foo' ... />
```

Then I can do this:
```javascript
window.jwplayer('foo')
``` 

to access the player instance itself

**Comment by tariqinaam** [comment]
That's awesome. It worked like charm.

**Comment by vtapia5070** [comment]
Hey @danmakenoise! Are there any tips for getting access to `window.jwplayer` within the class that renders the react-jw-player? Right now I am trying to access it within `componentDidMount`, but it is undefined. I do see it defined in the browser console after my javascript is run.

**Comment by danmakenoise** [comment]
@vtapia5070 thanks for the update! I'm not the best at writing README's, do you think we need some more info in it?

**Comment by vtapia5070** [comment]
@danmakenoise Your read me is great! It's just a small lack of JW player documentation on my part. I've submitted a small PR to update the README. Thanks!
