### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by benbristow** [micnews/react-jw-player#21]
Hey,

I've gotten this component working great with Chrome but I tried loading up a video player using Internet Explorer 11 and noticed it would not load.

The problem lies with the following line:

```javascript
return Object.assign(playerOpts, customProps);
```
https://github.com/micnews/react-jw-player/blob/master/src/helpers/get-player-opts.js#L45

Apparently Internet Explorer doesn't support `.assign`. Typical.

**Comment by danmakenoise** [comment]
@benbristow no problem, we can polyfill that, i'll push a fix this week

**Comment by danmakenoise** [comment]
Fixed by https://github.com/micnews/react-jw-player/pull/23
