### ISSUE TITLE
Pass an object to the playlist prop

### ISSUE THREAD

**Issue by dtamburr** [micnews/react-jw-player#30]
The `playlist` prop requires a valid link to a playlist `json` file. Would it be possible to pass a `playlist` object instead of a link string? I have self-hosted video files and I need to use a playlist to add captions (`.vtt` files).

Or would a `captions` or `tracks` prop be an option?

From [JWPlayer doc](https://support.jwplayer.com/customer/portal/articles/1407438-adding-closed-captions): 

```js
var playerInstance = jwplayer("myElement")
playerInstance.setup({
    playlist: [{
        file: "/assets/sintel.mp4",
        image: "/assets/sintel.jpg",
        tracks: [{ 
            file: "/assets/captions-en.vtt", 
            label: "English",
            kind: "captions",
            "default": true 
        },{ 
            file: "/assets/captions-fr.vtt", 
            kind: "captions",
            label: "French"
        }]
    }]
});
```

**Comment by dtamburr** [comment]
I managed to make it work by changing

```
playlist: PropTypes.string,
```
to
```
playlist: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.array,
]),
```

in https://github.com/micnews/react-jw-player/blob/master/src/prop-types.js#L37

**Comment by danmakenoise** [comment]
@dtamburr we've thought about doing this as well, I'm open to the feature, and made a comment on your PR
