### ISSUE TITLE
where is the demo？

### ISSUE THREAD

**Issue by niyingg** [micnews/react-jw-player#32]
I can't run the code.I didn't know what is the playerScript mean.

**Comment by danmakenoise** [comment]
@niyingg the playerScript is the URL for your copy of the JW Player script file. Do you self-host JW Player, or do you use the CMS currently?

**Comment by danmakenoise** [comment]
@ellell I'm going to close this one, okay with you?

**Comment by ellell** [comment]
@danmakenoise yup, closing!
