### ISSUE TITLE
Re-rendering [QUESTION]

### ISSUE THREAD

**Issue by andrerfneves** [micnews/react-jw-player#38]
Awesome package. Really works well with integration of React and JW. I do however need to change the video source of the player in my application quite a bit. Imagine a multiple-videos page. I want to `re-render` the VideoPlayer when I change the video on my Redux store. I have tried `this.forceUpdate()` and I've tried resetting/updating state but couldn't get it to work. Any ideas on how I'd go about doing this?

Is the better approach that I collect all of the videos and put them inside of a `playlist` and therefore wouldn't need to re-render the player?

**Comment by danmakenoise** [comment]
This might be a problem resulting from the fact that the video player itself is not a React component, but is completely handled by JW Player. If you want to change the video, you currently need to tap into the JW Player API, or unmount the player and mount a new instance of the component.

That said, there could be a case for the component automatically handling this when the props change. Would you be able to make a feature request for that? I'm sure you aren't the only one using it this way, and it'd be good to get some feedback from other users.

**Comment by andrerfneves** [comment]
@danmakenoise yeah that makes sense. For anyone that needs a quick workaround to this, I just used a `state` prop called `rerender`, and if you have a `video` prop coming into your `VideoPlayer` component abstraction, you can just run something like:

```js
componentWillReceiveProps(nextProps: Props) {
    if (this.props.video !== nextProps.video) {
      this.setState({ rerender: true }, () => {
        this.setState({ rerender : false })
      })
    }
  }
``` 

coupled with a render function like so:

```js
render() {
    const { rerender } = this.state
    return !rerender ? this._renderVideoPlayer() : null;
  }
```

It does re-render the video, but there's a quick white flash. I'll start looking into a nice fade alternative now. Shouldn't be too complicated.
