### ISSUE TITLE
On page scroll issue

### ISSUE THREAD

**Issue by gauravverma029** [micnews/react-jw-player#39]
Hi,
I am using you extension in my react project. Everthing is working fine but on my viewport screen  there are my 2 Videos.i want to run only one autoplay but now what is happing its running both in same time i want only one video should play at same when i scroll then second should play or pervious one should pause.

Second issus is -  if i mute the video and after scrolling  video is pause automatically it running.it should pause after scroll. in case of mute on.

**Comment by danmakenoise** [comment]
@gauravverma029 in order to create the on-scroll behavior and the muting behavior, you will need to interact with the JW Player API directly. See [here](https://github.com/micnews/react-jw-player/issues/20) for how to get access to it.

**Comment by michaelBenin** [comment]
@gauravverma029 we have something implemented which may solve your problem. It's being maintained in a fork though: https://github.com/fastcompany/react-jw-player/commit/fe9b795aae80a569d286614a5ad2882bb8110ca0

**Comment by danmakenoise** [comment]
@michaelBenin hey! would you be willing to turn your additional features into a wrapper component around ReactJWPlayer? My thinking is you could publish the wrapper component, and we could link to it here to help out other dev teams that may want to do something similar.

**Comment by danmakenoise** [comment]
@ellell thinking we can close this one too, since its outside the scope of what we want this component to do

**Comment by ellell** [comment]
@danmakenoise yes, I agree with that.
