### ISSUE TITLE
Support 'vast' ads

### ISSUE THREAD

**Issue by fairbairn** [micnews/react-jw-player#46]
Looks like the advertisement settings under the implementation are hard-coded to support only google, yet docs say we can use callback to provide a VAST tag (url).

We need the client to be 'vast' for that to work.

**Comment by orrybaram** [comment]
We should probably let users define an `advertising` prop that sets custom options.
See https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#advertising

**Comment by orrybaram** [comment]
@fairbairn I created a PR to add this functionality, and while doing so realized that you can override the defaults by passing in an advertising object to `customProps`.
https://github.com/micnews/react-jw-player#optional-configuration-props

**Comment by danmakenoise** [comment]
@fairbairn Were problems were you having with ads running on the default settings? In our experience, having it set to `googima` hasn't prevented the player from using Vast tags. But, our use case isn't everyone's use case.

**Comment by danmakenoise** [comment]
@orrybaram I think using customProps is the better way to override defaults like this, but we should add something to the docs describing how to do that. I think for v2 we are going to rely on customProps much more since it keeps us a little less coupled with JW Players API

**Comment by orrybaram** [comment]
Makes sense, I closed out the PR.

**Comment by danmakenoise** [comment]
@orrybaram can you pr a readme change with how to override? if not, I can do it.

**Comment by danmakenoise** [comment]
@fairbairn did using customProps work for you? If so, I'm going to close this out.

**Comment by fairbairn** [comment]
You can close it out.  We elected to import and use the JWPlayer.js
directly to have better control.


You dream it.  We build it!

Breakthrough Technologies
breakthrough-tech.com

**Comment by danmakenoise** [comment]
Sounds good! Thank you for the update.
