### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by ProdigyView** [micnews/react-jw-player#49]
The JWPlayer has a paramter for Google Anaytlics:

```
var playerInstance = jwplayer("myElement");
playerInstance.setup({
    file: "/uploads/example.mp4",
    image: "/uploads/example.jpg",
    ga: {} 
});
```

Is there any likelihood of being able to do the same with this implementation?

**Comment by danmakenoise** [comment]
@ProdigyView you should be able to do this like this:

```
<ReactJWPlayer
  customProps={{
    ga: {}
  }
/>```

Can you give that a try?

**Comment by danmakenoise** [comment]
@ellell planning on closing this one too.

**Comment by danmakenoise** [comment]
Closing as a solution is available above.
