### ISSUE TITLE
Icon not rendering

### ISSUE THREAD

**Issue by ssageghi** [micnews/react-jw-player#52]
Hi
thanks for your component 
I used it and I have a problem with it
the player Icon does not show correctly
![image](https://user-images.githubusercontent.com/24605214/30055414-9b6eac2a-9244-11e7-824a-668db0893bff.png)

**Comment by danmakenoise** [comment]
@ssageghi any problems with the player display should be related to JWPlayer's player script itself. It looks some of the assets for the player aren't loading properly in your case.

**Comment by ssageghi** [comment]
@danmakenoise 
are these related to each other 
I get this Error in my console 
![image](https://user-images.githubusercontent.com/24605214/30096388-5b96cd0e-92ed-11e7-8ef3-e073853a6be9.png)

**Comment by danmakenoise** [comment]
@ssageghi if `window.jwplayer` isn't available then the jw player sdk hasn't loaded properly. Can you verify that your playerScript file is loading properly?

**Comment by suhanivar07** [comment]
@danmakenoise @ssageghi Icons are not getting rendered in my case too.
<img width="960" alt="icon" src="https://user-images.githubusercontent.com/31689321/35092706-42d65978-fc66-11e7-9d93-9342ef6a3a83.png">

**Comment by danmakenoise** [comment]
@suhanivar07 this is most likely still an issue with JWPlayer itself and not this library. Can you post your code, and a full error log from running your code?

**Comment by suhanivar07** [comment]
@danmakenoise  Yes It was the problem with my JWplayer script.It is fixed now. 

But it is only supporting mp4 formats not "smil"

**Comment by danmakenoise** [comment]
Okay closing this! Thank you for the reply!
