### ISSUE TITLE
Version 2 Proposal

### ISSUE THREAD

**Issue by danmakenoise** [micnews/react-jw-player#54]
Hey gang!

We are about to get started building version 2 of this and I wanted to get some discussion going about a few things:

1. A personal goal of mine is to decouple this component from JW Player's API much as possible. One way we've coupled the component pretty tightly is by making a lot of defaults in the configuration options. I think in version 2, it will be better to not override any defaults from player scripts and just let users add in their out config vis `customProps`. This will prevent us from having to add in a new component property for every single config option, over time.

1. I also want to break out a base component from a wrapper component. My thought is that the base component `ReactJWPlayerBase` would ONLY map props to JW Player Event hooks. This component will be a great option for anyone looking to really customize the component. The second component could be just `ReactJWPlayer`, and we would move all of the "nice to have" functionality, like `onFiftyPercent`, having preroll automatically generated, etc.

This set up would allow us to decouple the base component from JW Player as much as possible, and allow us to have the container component more or less completely decoupled.

So here is what I would like some feedback on, including some other utility things.

1. Should we break out `ReactJWPlayer` and `ReactJWPlayerBase`. How do we feel about those titles? How do we feel about the separation of logic between them.
1. I'm considering changing up the linter from `miclint` to using eslint with an `.eslintrc` file directly. This should make contributing a little easier for those that have IDE's set up to automatically read and lint based upon `.eslintrc`
1. I would like to add Flow typing to the component.
1. I'm considering switching the testing library to Jest, after finding some pretty great productivity enhancements in my personal time. I don't have an issue with keeping `tape` if people feel strongly one way or the other.
1. Since this will be a major version, is there anything else we should change?

**Comment by danmakenoise** [comment]
@nirarazi @tomconroy @michaelbenin @dtamburr @zentuit @vtapia5070 @chrisdugne @juzzyo-ffm @alinchican @petertdinh @duongthienduc 

If any of you have any opinions on this stuff, let me know!

**Comment by tomconroy** [comment]
Cool, we would indeed much prefer transparent mapping to player props such as `onTime` rather than `onThreeSeconds`

**Comment by michaelBenin** [comment]
Hey @danmakenoise - so sorry for the late response! 

Everything outlined above sounds great. 

Sounds like this component will load in the external js files and just keep a reference to the player no? 

One request - is it possible to use prettier with eslint config? 

I would be happy to help set that up.

**Comment by danmakenoise** [comment]
@michaelBenin to clear up things, here is how I envision the API being for the base component.

```
<ReactJWPlayer
  playerScript='https://...foobar.js'
  eventHandlers={{
    onPlay: this.onPlay,
    onPause: this.onPause
  }}
  playerConfig={{
    autoplay: false
    muted: true
  }}
/>
```

As far as prettier goes, I'm open to giving it a shot, but probably would want to address separate from this version launch. I'd like to hear from others on why we should or shouldn't move that way. Mind making an issue just for that?

**Comment by danmakenoise** [comment]
Work has started on this https://github.com/micnews/react-jw-player/pull/60

**Comment by danmakenoise** [comment]
@ellell, not certain this is worth developing right now, since we haven't really run into any issues with the current setup. Wdyt?

**Comment by ellell** [comment]
@danmakenoise Yea, I'm good with putting this on ice!

**Comment by danmakenoise** [comment]
Okay, closing for now until we see a pressing need for a rewrite.
