### ISSUE TITLE
Specifying the file to play when a playlist is defined 

### ISSUE THREAD

**Issue by m2jobe** [micnews/react-jw-player#61]
Is specifying the video to play in a set playlist possible 

```
  <ReactJWPlayer
    playerId='my-unique-id'
    playerScript='https://link-to-my-jw-player/script.js'
    playlist='https://link-to-my-playlist.json'
  />
```

And if not then is it possible to play a video hosted in jwplayer just from the video ID?

**Comment by m2jobe** [comment]
For example in this library that functionality is possible: https://github.com/noahfeder/react-jwplayer

`  <JWPlayer videoId="<your-id-here>" />,
`

**Comment by m2jobe** [comment]
If the full video path is needed how do we generate it based on the ID?

**Comment by danmakenoise** [comment]
@m2jobe You can do this a couple of ways:

The best we have found is to use the playlist option with the JSON playlist that JW Player automatically makes for each video. You get more metadata that way:
`playlist='http://content.jwplatform.com/feeds/<media-id>.json'`

You can also get the m3u8 file from the jwplayer CMS and pass that to the file prop.

**Comment by m2jobe** [comment]
Your first suggestion was just what I was looking for however the colour design of the player doesn't seem to come through.

Unrelated but this was useful for my use case with social sharing on the player, after contacting customer support, to ensure the social sharing link is your website and not content.jwplayer you need to add the following in helpers/get-player-opts.js

`  playerOpts.sharing = {link : ""}
`
See: https://github.com/m2jobe/react-jw-player/commit/a31d416c79d01eee2cb1d98bc3a2a6a46cf2455d#diff-65f88a71b9392826feb1b4757deb6ffa

**Comment by danmakenoise** [comment]
@m2jobe can you see if you can accomplish this using `customProps`?

`<ReactJWPlayer
  customProps={{
    sharing: {
      link: ''
    }
  }}
/>```

**Comment by m2jobe** [comment]
Yes that works just fine, I should've read into the documentation more!

**Comment by danmakenoise** [comment]
@m2jobe no worries, it's buried pretty deep! Do you think it's worth it to be a note in about this behavior into the README?

**Comment by m2jobe** [comment]
@danmakenoiseYes I think that would be useful!
