### ISSUE TITLE
Video won't play on Iphone

### ISSUE THREAD

**Issue by christchron** [micnews/react-jw-player#63]
Some of my videos cannot be played on Iphone. It show's File could not be played. But it works fine on laptop. Anyone know how to solve it?

**Comment by danmakenoise** [comment]
What kind of file and/or playlist are you trying to load?

**Comment by christchron** [comment]
@danmakenoise the file format is .m3u8

**Comment by danmakenoise** [comment]
@christchron definitely have seen similar weirdness with m3u8 files, is the video hosted by JW Player?

**Comment by christchron** [comment]
@danmakenoise nope, its my own videos.

**Comment by danmakenoise** [comment]
@christchron yeah, i think this is an issue with JW Player itself then, and not the component. Hopefully someone else might have some insight?

**Comment by christchron** [comment]
ok then if no one can solve it here, thanks btw @danmakenoise !

**Comment by danmakenoise** [comment]
@christchron no problem. Like I said, we had trouble with using direct m3u8 files on mobile as well, which is why we switched to JSON playlists.
