### ISSUE TITLE
Setting HD toogle 

### ISSUE THREAD

**Issue by christchron** [micnews/react-jw-player#67]
Hi, I want to ask about how to set the video quality in react jwplayer. In my player, it shows the hd button but didn’t show the quality options. Can you tellme how to add the quality options?

**Comment by danmakenoise** [comment]
@christchron that's an issue with JW Player itself, and not this wrapper. But, I still might be able to help! What kind of file are you loading into the player?

**Comment by christchron** [comment]
@danmakenoise the file I'm using is m3u8 file. Can you tell me what kind of file that JW player hosted?

**Comment by danmakenoise** [comment]
`m3u8` should do the trick, are you looking at desktop or mobile?

**Comment by danmakenoise** [comment]
Closing since we don't have enough information to debug this.
