### ISSUE TITLE
player.on is not a function

### ISSUE THREAD

**Issue by brunolucena** [micnews/react-jw-player#70]
No initialize, o componente não está reconhecendo as chamadas de player.on:

```
player.on('beforePlay', _onBeforePlay);
player.on('ready', component.props.onReady);
player.on('setupError', component.eventHandlers.onError);
...
```

Tentei alterar cada chamada para o nome da função, e algumas funcionaram, mas o player continua com erro. Ex:
`player.on('beforePlay'...)` para `player.onBeforePlay('beforePlay')`

Não consegui localizar onde o player deveria chamar essas funções.
Agradeço ajuda.

**Comment by danmakenoise** [comment]
Olá, desculpe as traduções ruins aqui, estamos usando o Google Translate para ajudar.

Tudo isso parece estar funcionando corretamente em nossos testes. Você pode nos dar quaisquer mensagens de erro que está a ver?

**Comment by brunolucena** [comment]
Sorry, I can speak in english.
I was using JWplayer version 6. Updated to version 7 and the error is gone. I believe there is no support to v6 right.
Thanks for the help.

**Comment by danmakenoise** [comment]
@brunolucena that makes sense! We built this for version 7, and it is compatible with 8 as well.

**Comment by danmakenoise** [comment]
Closing this, as we have no intention to support JW Player version 6 currently.
