### ISSUE TITLE
Is custom skinning supported.

### ISSUE THREAD

**Issue by rahulsinghvuclip** [micnews/react-jw-player#75]
Hi Team,
I want to customise the skining in jwplayer.Is it supported.

**Comment by danmakenoise** [comment]
@rahulsinghvuclip sure thing, you should be able to use customProps like this:

```js
<ReactJWPlayer
  // normal code here
  customProps={{
    skin: {
      controlbar: {
        text: '#FFFFFF'
      }
    }
 }}
/>
```

[Here is what is allowed in JW Player itself](https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/#skin)

**Comment by rahulsinghvuclip** [comment]
When i setting height and width....it is not taking css

**Comment by danmakenoise** [comment]
@rahulsinghvuclip what is the code you are trying to use?

**Comment by rahulsinghvuclip** [comment]
I am trying to pass this config
 config = {
  playerId: '1',
  isAutoPlay: true,
  className: 'jwp',
  width: 160,
  height: 90,
  playerScript:
    'https://vuclip-a.akamaihd.net/viuembed/webplayer/assets/jwplayer-8.0.0/jwplayer.js',
  licenseKey: 'kQB2AygqogBc1g19AlzMq30H/9Rl0JnpD6XUFw==',
  file: 'http://vjs.zencdn.net/v/oceans.mp4',
  image: 'http://vjs.zencdn.net/v/oceans.png',
  customProps: {
    skin: { name: 'Small' }
  }
};


But hieght and width are not applying ..Remaining thing is fine.

**Comment by rahulsinghvuclip** [comment]
Thanks i have resolved the issue through custom css.

But fullScreen is throwing errror..It is not working.

**Comment by danmakenoise** [comment]
@rahulsinghvuclip okay, great! I will close this out!
Can you make separate issue for the problem with `fullScreen`
Please include any code you are using if you can, and any error messages!
