### ISSUE TITLE
FullScreen functionlity is not working.

### ISSUE THREAD

**Issue by rahulsinghvuclip** [micnews/react-jw-player#76]
Hi team.
My  code is below.
const config = {
  playerId: '1',
  isAutoPlay: true,
  className: 'jwp',
  width: 160,
  height: 90,
  playlist: [
    {
      file: 'http://vjs.zencdn.net/v/oceans.mp4',
      image: 'http://vjs.zencdn.net/v/oceans.png',
      tracks: [
        {
          file: 'https://link-to-subtitles.vtt',
          label: 'English',
          kind: 'captions',
          ' default': true
        }
      ]
    },
    {
      file: 'http://vjs.zencdn.net/v/oceans.mp4',
      image: 'http://vjs.zencdn.net/v/oceans.png'
    }
  ],
  playerScript:
    'xxx/jwplayer.js',
  licenseKey: 'kQB2==',
  customProps: {
    skin: { name: 'Small' }
  }
};

class VideoPlayer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      videoTitle: ''
    };
    this.player = '';
    this.onAdPlay = this.onAdPlay.bind(this);
    this.onReady = this.onReady.bind(this);
    this.onVideoLoad = this.onVideoLoad.bind(this);
    this.handleClick = this.handleClick.bind(this);
    // each instance of <ReactJWPlayer> needs a unique id.
    // we randomly generate it here and assign to the container instance.
    this.playerId = '1';
  }
  onReady(event) {
    // interact with JW Player API here
    this.player = window.jwplayer(config.playerId);
    const playerContainer = this.player.getContainer();
    const displayC = playerContainer.querySelector('.jw-display-controls');
    console.log(displayC);
    const rewindC = displayC.querySelector('.jw-display-icon-rewind');
    const nextC = displayC.querySelector('.jw-display-icon-next');
    console.log(rewindC);
    const captionC = playerContainer.querySelector('.jw-icon-cc');
    const fullscreen = playerContainer.querySelector('.jw-icon-fullscreen');
    fullscreen.className += ' jw-display-icon-container';
    captionC.className += ' jw-display-icon-container';
    console.log(event);
    console.log(this.player);
    displayC.replaceChild(captionC, rewindC);
    displayC.replaceChild(fullscreen, nextC);
  }
  onAdPlay(event) {
    console.log(event);
  }
  onVideoLoad(event) {
    this.setState({
      videoTitle: event.item.description // this only works with json feeds!
    });
  }
  handleClick = (e, eve) => {
    console.log(e.target);
    e.target.style.display = 'none';
    const elem = document.getElementById(eve);
    alert(elem);
    elem.parentNode.removeChild(elem);
  };

  render() {
    return (
      <div className="react-jw-player-container">
        <h1>{this.state.videoTitle}</h1>
        <div>
          <button
            id="removebtn"
            onClick={e => {
              this.handleClick(e, this.playerId);
            }}
          >
            Remove(x)
          </button>
        </div>
        <ReactJWPlayer
          {...config}
          onAdPlay={this.onAdPlay}
          onReady={this.onReady}
          onVideoLoad={this.onVideoLoad}
        />
      </div>
    );
  }
}

VideoPlayer.displayName = displayName;

export default VideoPlayer;

**Comment by danmakenoise** [comment]
Hey two things!

1.) Can you wrap all the code in code formatting? Put ``` before and after the code.
2.) Might want to hide your JW Player License key!

I'll take a look at the code.

**Comment by danmakenoise** [comment]
It looks like you are replacing the fullScreen button with the nextButton, is that right?
`displayC.replaceChild(fullscreen, nextC);`

**Comment by rahulsinghvuclip** [comment]
Yes...But in normal scenario also full screen is not working

**Comment by rahulsinghvuclip** [comment]
It's quite amazing that this issue is reported by me only on both github pages react jw as well as jw player.. And both referencing this each other. #2592 is raised by me only... Jw support saying its react jw player issue

**Comment by danmakenoise** [comment]
@rahulsinghvuclip is there any chance you can get a demo up online?

If I take your code, and remove these two lines:
```
displayC.replaceChild(captionC, rewindC);
displayC.replaceChild(fullscreen, nextC);
```

The fullscreen button works as expected with both JWPlayer 7 & 8.

If you can find a way to get a live demo, we may be able to help you out. We would also need to know what browser and device you are using to be sure.

**Comment by rahulsinghvuclip** [comment]
I am using chrome browser version 62 on windows 8.1

**Comment by danmakenoise** [comment]
@rahulsinghvuclip can you see if any console errors pop up when you click the fullscreen button on your end? Sorry, I just can't help if I can't recreate the problem, but I can maybe help you debug it.

**Comment by rahulsinghvuclip** [comment]
This is the url.
https://rahul123player.herokuapp.com/

I am using only react-jw-player component.
full screen is not working properly.

**Comment by rahulsinghvuclip** [comment]
@danmakenoise any update on this.

**Comment by danmakenoise** [comment]
@rahulsinghvuclip I responded to JW Player in this thread: https://github.com/jwplayer/jwplayer/issues/2592. It appears to be a problem with the player code itself, not our library. But, I'd like their input.

**Comment by rahulsinghvuclip** [comment]
@danmakenoise  any update on this

**Comment by danmakenoise** [comment]
@rahulsinghvuclip figured it out!

The player id cannot be a number in string format. `player-1` works fine, `1` breaks some logic somewhere in JW Player. I'll file an issue for that.

**Comment by danmakenoise** [comment]
@rahulsinghvuclip i'm closing this out, made an issue for this in JW Player here https://github.com/jwplayer/jwplayer/issues/2618

**Comment by zameerSheikh** [comment]
@danmakenoise aspectRatio, width, height are not working.
