### ISSUE TITLE
Uncaught TypeError: n.setup is not a function - React 16

### ISSUE THREAD

**Issue by El-Gregory** [micnews/react-jw-player#77]
Ever since our upgrade to React 16 our app is throwing this error on our SPA app's page load. If we click into it from another page it loads correctly but refresh breaks the whole page. I've wrapped the jwplayer in react ErrorBoundary tags in order allow our pages to load but the underlying problem still exists. 

The error is in this block of prettytified code.

"./node_modules/react-jw-player/dist/helpers/initialize.js": function(e, t, n) {
        "use strict";
        Object.defineProperty(t, "__esModule", {
            value: !0
        }),
        t.default = function(e) {
            var t = e.component
              , n = e.player
              , o = e.playerOpts;
            n.setup(o), // Here
            n.on("beforePlay", function(e) {
                t.eventHandlers.onBeforePlay(e, n)
            }),
            n.on("ready", t.props.onReady),
            n.on("setupError", t.eventHandlers.onError),
            n.on("error", t.eventHandlers.onError),
            n.on("adPlay", t.eventHandlers.onAdPlay),
            n.on("adPause", t.props.onAdPause),
            n.on("adSkipped", t.props.onAdSkipped),
            n.on("adComplete", t.props.onAdComplete),
            n.on("fullscreen", t.eventHandlers.onFullScreen),
            n.on("pause", t.props.onPause),
            n.on("play", t.eventHandlers.onPlay),
            n.on("mute", t.eventHandlers.onMute),
            n.on("playlistItem", t.eventHandlers.onVideoLoad),
            n.on("time", t.eventHandlers.onTime),
            n.on("beforeComplete", t.props.onOneHundredPercent),
            n.on("buffer", t.props.onBuffer),
            n.on("bufferChange", t.props.onBufferChange)
        }
    }

We're not doing anything different since the upgrade as far as I can tell. Another thing I should note is that we're an isomorphic app and it works in debug mode where everything is processed and rendered on the client but not in prod mode where everything is processed on the server and pushed to the client for rendering. I saw weird setup errors from this before but I think previous versions of react were more permissive. 

My guess is something isn't checking if it's in a browser or not before firing setup but it's only a guess. 

We're running 
"react": "^16.0.0",
"react-jw-player": "^1.16.0",

and a hosted version of jwplayer-7.12.11

Any help or advice would be appreciated.

**Comment by danmakenoise** [comment]
@El-Gregory do you have a live version of this up anywhere? That might help me debug this with you.

If not, can I see the code where you use `react-jw-player`?

**Comment by El-Gregory** [comment]
I can pm you a link (i don't want to get it indexed) but here is my react-jwplayer component. Maybe it can tell you what we're doing wrong:

@connect(state => ({
  clientApiOrigin: state.config.clientApiOrigin,
  navigation: state.navigation,
  user: state.auth.user,
}))
export default class JWPlayer extends Component {
  static propTypes = {
    clientApiOrigin: PropTypes.string.isRequired,
    navigation: PropTypes.object.isRequired,
    playlist: PropTypes.array,
    mavenMediaId: PropTypes.string,
    width: PropTypes.string,
    height: PropTypes.string,
  }
  constructor(props) {
    super(props);
    const { playlist, mavenMediaId, navigation } = this.props;
    const { currentChannelKey, currentConversationId, currentRoomKey } = navigation
    const file = playlist && playlist.file

    this.state = {
      active: false,
    };

    // each instance of <ReactJWPlayer> needs a unique id.
    // we randomly generate it here and assign to the container instance.
    this.playerId = `jw-player-${Math.random().toString().slice(8)}`
    this.label = [currentChannelKey, currentRoomKey, currentConversationId, mavenMediaId, file].filter(Boolean).join('/')
  }

  render() {
    const jwplayerkey = [License Key]
    const jwplayerscript = '/cdn/js/jwplayer-7.12.11/jwplayer.js'
    const { clientApiOrigin, playlist, width, mavenMediaId, navigation, height } = this.props;
    const { currentChannelKey, currentConversationId, currentRoomKey } = navigation

    if (!playlist && !mavenMediaId) {
      return null
    }

    const file = playlist && playlist.file
    const label = [currentChannelKey, currentRoomKey, currentConversationId, mavenMediaId, file].filter(Boolean).join('/')
    let isAudio
    if (file) {
      const type = GetTypeFromUrl(file)
      isAudio = type && type.startsWith('audio')
    }
    const category = isAudio ? UserEventCategory.Audio : UserEventCategory.Video

    // player interaction events
    const onPlay = () => {
      this.setState({
        active: true
      })
      context.eventHelper.logEvent({
        category,
        type: UserEventType.Play,
        label,
      })
    }

    // Percent watched events
    const onTwentyFivePercent = () => {
      context.eventHelper.logEvent({
        category,
        type: UserEventType.PlayPercent,
        label,
        value: 25
      })
    }

    const onFiftyPercent = () => {
      context.eventHelper.logEvent({
        category,
        type: UserEventType.PlayPercent,
        label,
        value: 50
      })
    }

    const onSeventyFivePercent = () => {
      context.eventHelper.logEvent({
        category,
        type: UserEventType.PlayPercent,
        label,
        value: 75
      })
    }

    const onNinetyFivePercent = () => {
      context.eventHelper.logEvent({
        category,
        type: UserEventType.PlayPercent,
        label,
        value: 95
      })
    }

    const onOneHundredPercent = () => {
      context.eventHelper.logEvent({
        category,
        type: UserEventType.PlayPercent,
        label,
        value: 100
      })
    }
    const aspectratio = width && height ?
      `${width}:${height}` : '16:9'
    const customProps = {
      skin: {
        name: 'seven',
      },
      width: '100%',
      aspectratio
    }

    return (
      <div className={classNames('react-jw-player-container', { active: this.state.active })}>
        <ReactJWPlayer
          playlist={playlist || `${clientApiOrigin}/media/jwplaylist/${mavenMediaId}`}
          licenseKey={jwplayerkey}
          playerId={this.playerId} // bring in the randomly generated playerId
          playerScript={jwplayerscript}
          onPlay={onPlay}
          onTwentyFivePercent={onTwentyFivePercent}
          onFiftyPercent={onFiftyPercent}
          onSeventyFivePercent={onSeventyFivePercent}
          onNinetyFivePercent={onNinetyFivePercent}
          onOneHundredPercent={onOneHundredPercent}
          customProps={customProps}
        />
      </div>
    );
  }
}

**Comment by danmakenoise** [comment]
@El-Gregory can you try ruling out that the randomly generated ID on server is causing issues? I'm wondering if server and client are coming up with different ones.

**Comment by El-Gregory** [comment]
@danmakenoise 
Sure. I was wondering that myself but the output always "seemed" the same when I'd log it. I'll try that right now.

**Comment by El-Gregory** [comment]
@danmakenoise I think that may have been it!!! Let me play with it a bit more to verify.
