### ISSUE TITLE
Please rename `prop-types.js` to something else

### ISSUE THREAD

**Issue by zentuit** [micnews/react-jw-player#80]
Webpack has a bug (that I'm trying to get tracked down) where the resolution graph gets messed up and results in `prop-types` trying to require itself.

React's `prop-types` is moduleId 48 and react-jw-player's `prop-types` is moduleId 527. Instead of 
```
var _propTypes = __webpack_require__(48);
```
I'm getting
```
var _propTypes = __webpack_require__(527);
```
Here's the snippet:
```
/***/ }),
/* 527 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
  value: true
});

var _propTypes = __webpack_require__(527);

var _propTypes2 = _interopRequireDefault(_propTypes);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var propTypes = {
  aspectRatio: _propTypes2.default.oneOf(['inherit', '1:1', '16:9']),
  className: _propTypes2.default.string,
<snip rest>
```
While I realize this isn't technically your issue, it would help resolve what I'm seeing.  Otherwise I'm going to have to fork until the webpack bug is found and fixed. 😞

**Comment by ryanscottaudio** [comment]
@zentuit Should be all good now, just upgrade to the latest version of the library.

**Comment by ellell** [comment]
Fixed in https://github.com/micnews/react-jw-player/pull/82
