### ISSUE TITLE
to catch setupError

### ISSUE THREAD

**Issue by rahulsinghvuclip** [micnews/react-jw-player#85]
Hi team , I want to log setuperror. any solution

**Comment by danmakenoise** [comment]
@rahulsinghvuclip you can always use the standard `window.jwplayer` API to add event listeners!

In this case it would be: 

```
window.jwplayer(PLAYER_ID).on('setupError', yourFunctionToRun);
```

**Comment by rahulsinghvuclip** [comment]
but where to add these code..onReady() is not loaded

**Comment by rahulsinghvuclip** [comment]
@danmakenoise can you help me out where to call this api as before onready window.jwplayer is not available

**Comment by rahulsinghvuclip** [comment]
@danmakenoise yes ,onError is called if there is error during playback but to catch setuperror we need to add hooks.

**Comment by rahulsinghvuclip** [comment]
@danmakenoise similarlry onBeforePlay() can be passed to props as we dont have now.

**Comment by kylane** [comment]
Anyone else finding onError isn't firing when jwplayer has an error event?
