### ISSUE TITLE
How to set the license key

### ISSUE THREAD

**Issue by busyoumono99** [micnews/react-jw-player#9]
Is there a way to set the license key? Is there such a api?

**Comment by danmakenoise** [comment]
Currently this doesn't support handling the license key. Right now, it is built with the assumption that  you are using one of the prebuilt player scripts provided through the JW Player CMS. (That's how we use it at Mic)

You should be able to set up the script with your license key outside of the component within your html. Try that, and let me know if it works. If not, we can work together to find a way to implement that here!

**Comment by gauravmittal470** [comment]
I'm using jwplayer-7.10.4 with react js and it doesn't work without the license key. I didn't find any way to add the key.
Can you help me in adding the license key to the jwplayer?

**Comment by idangozlan** [comment]
@danmakenoise it's making your module non usable. I think that license key is mandatory for most of the cases.

**Comment by danmakenoise** [comment]
@idangozlan The module is usable when you use the JW Player hosted SDK, which doesn't require the license key. I will look into supporting self-hosted SDK's with a license key so that this isn't blocking!

**Comment by danmakenoise** [comment]
Fixed by https://github.com/micnews/react-jw-player/pull/22
