### ISSUE TITLE
Not resizing for responsive devices

### ISSUE THREAD

**Issue by eagle1000** [micnews/react-jw-player#91]
Hello,
I am having trouble when using react-jw-player as my player is not resizing for mobile devices.  It is maintaining a fixed width and height.  I am attaching a screenshot from my jw dashboard to show the player version I am using (8.1.8) and that it is configured to be responsive.  The player resizes fine outside of react when simply using the embed code from the jw dashboard.  
Here is the code I am using.  As you can see, I am just creating a basic component to play a specific file.  (license key has been omitted).  The video plays fine except for not resizing. Is there anything additional that needs to be done to have the player auto resize?  Thank you!

```jsx
import React from "react";
import ReactJWPlayer from 'react-jw-player';

const key = 'abc123';
const JWPlayer = props => (
 	  <div>
           <ReactJWPlayer
              className="jw-player"
              licenseKey={key}
              playerId='Test1'
              playerScript='https://content.jwplatform.com/players/EnaV52f7-gVbyfBkc.js"'
              file='https://content.jwplatform.com/manifests/EnaV52f7.m3u8'
             />
    </div>
);
export default JWPlayer;
```

![jwplayer](https://user-images.githubusercontent.com/30674397/36605899-b2ab834e-1887-11e8-8eaa-6188e641ca35.JPG)

**Comment by akroll1** [comment]
Same issue here. Player is fixed size, not dynamic as in the past.

**Comment by danmakenoise** [comment]
@akroll1 @eagle1000 would either of you be able to set up a live demo link so we can debug this?

**Comment by eagle1000** [comment]
HI,
Here is a link for you to preview the issue.  Many thanks!
[https://sleepy-earth-81897.herokuapp.com/canciones-infantiles/pin-pon]

**Comment by danmakenoise** [comment]
@eagle1000 okay! I see the issue! The JW Player instance will only be responsive as long as the div it is contained with is as well. Since you have a fixed height and width on the containing div, it is always taking up 100% of that space, even when the viewport is less than that.

To solve the issue, make sure the container that you place the component into has responsive height and width.

**Comment by eagle1000** [comment]
I have created a bootstrap column class for the div containing the component but this does not seem to solve the problem.  Attached is a screenshot showing the fixed dimensions are actually coming from the div INSIDE the component, despite the fact that the player is configured in the dashboard to be responsive and not fixed. (Screenshot on initial comment).  Thanks for your help!

![jwplayer1](https://user-images.githubusercontent.com/30674397/36645461-d2f5091a-1a2e-11e8-8281-3477b41abba0.JPG)

**Comment by danmakenoise** [comment]
@eagle1000 your playerscript looks like it has a video hardcoded into it: `https://content.jwplatform.com/players/EnaV52f7-gVbyfBkc.js` can you switch that out with a base player script file, with no precoded video? I believe that is overriding your responsive settings.

**Comment by eagle1000** [comment]
@danmakenoise yes, that did solve the issue.  Thank you for your help and congratulations, it is an excellent package!
