### ISSUE TITLE
onPlaylistComplete event

### ISSUE THREAD

**Issue by adamnbowen** [micnews/react-jw-player#92]
I noticed that this library doesn't have an [onPlaylistComplete event](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeronplaylistcomplete) that is present in the jwplayer API documentation. Are you open to a pull request adding it, or do you have a specific reason for omitting it?

I also noticed you're missing "seek", but I suppose I can just use onPause and onPlay for that, most likely.

**Comment by danmakenoise** [comment]
@adamnbowen no particular reason other than no one had requested it yet. We are currently considering dynamically allowing props to be added. See #93 

If we pursue that path, then `playlistComplete` can be passed through as the prop `onPlaylistComplete` without needing to explicitly add it into the code. In the meantime, if you want to make a PR to handle it explicitly, that could get it up and running sooner, as I expect there to be some discussion around the dynamic props.

**Comment by adamnbowen** [comment]
Since #93 has been merged, and it solves my problem, I'm closing this.
