### ISSUE TITLE
Set Appearance: streching

### ISSUE THREAD

**Issue by nolate** [micnews/react-jw-player#94]
Hey

According to [docs](https://developer.jwplayer.com/jw-player/docs/developer-guide/customization/configuration-reference/) default streching should be `uniform` but what I see in my inspector elements tab is  `<video class="jw-video jw-reset" src="blob:http://localhost:3000/blabla" jw-loaded="data" style="object-fit: fill;"></video>`. I found nothing about setting the `object-fit` in the code I'm working on and neither found any apperance in the react-jw-player node module.

Should I call `jwplayer("myElement").setup()` and set streching or is there a way to do it in for e. g.   `<ReactJWPlayer customProps={{}} />`

Thanks!

**Comment by ellell** [comment]
@nolate Yes, you should be able to use the customProps to set stretching. Like this: `<ReactJWPlayer customProps={{ stretching: 'uniform' }} />`.

**Comment by nolate** [comment]
Thanks for the fast response @ellell !
Sorry to say but that doesn't work for me.

My setup:
`react-jw-player "version": "15.6.2"`

```
        <ReactJWPlayer
          ref={"jwplayer"}
          playerId={"jw-player-instance-" + this.props.type}
          className="no-subcription-container"
          isAutoPlay={true}
          onAutoStart={this.onAutoStart}
          onReady={this.onReady}
          onEnterFullScreen={this.onEnterFullScreen}
          onExitFullScreen={this.onExitFullScreen}
          customProps={{
            skin: {
              name: 'vidName',
              active: '#bee700',
              inactive: '#ffffff',
              background: 'transparent'
            },
            stretching: 'uniform',
            autostart: true,
            mute: true
          }}
          playerScript='https://blabla'
          playlist={things}
          licenseKey="key"
        />
```

But the video element still has the `style="object-fit: fill;"`

**Comment by ellell** [comment]
@nolate What version of the jwplayer js api are you using? I've tested it on version 7 which seems to work, but haven't yet tested it on version 8.

**Comment by nolate** [comment]
@ellell 
I'm using `react-jw-player"version": "1.12.0"` but I don't know what version of JW JS API is that using.

**Comment by nolate** [comment]
Fun fact, it only happens on my computer in chrome browser. We've tested in production on several computers without my changes and it happens only in chrome only on my PC when all extensions are turned off. So it's not the player. 

I was looking for the `stretch: 'uniform'` in the wrong place, it's there on the container. 
If I check my `<video>` element inside the `onReady` function there's no style attribute on it. It's appended 1-2 secs later.

![image](https://user-images.githubusercontent.com/16878884/37152816-e0b5f24e-22da-11e8-9fe3-95f73395afc0.png)

**Comment by ellell** [comment]
@nolate oh interesting. 

Well, sounds like this isn't a problem with `react-jw-player` anyways. As far as I can see we're not setting the stretching prop (or `object-fit` style) unless passed through `customProps`. I'd suggest checking in at https://github.com/jwplayer/jwplayer if this keeps being an issue for you.
