### ISSUE TITLE
TypeError: Cannot read property 'defaults' of undefined

### ISSUE THREAD

**Issue by nirarazi** [micnews/react-jw-player#96]
Happens while executing `setJWPlayerDefaults`.
Anyone else getting this?
Started today...

**Comment by ellell** [comment]
@nirarazi What version of jw-player are you using?

**Comment by danmakenoise** [comment]
@nirarazi did you ever get this resolved? Can we close this issue or is it still happening for you?

**Comment by nirarazi** [comment]
@danmakenoise I guess it is old enough to close it. Can't even remember how we've dealt with it.
