### ISSUE TITLE
On first time load in a mobile device, Audio player is set to mute by default.

### ISSUE THREAD

**Issue by nveen** [micnews/react-jw-player#97]
We are using JW Player as an audio player. We have some custom buttons for audio controles at the frontend but at the backend we are using JW Player to play the audio. We have an issue with the player in mobile devices. On first time loading the audio starts to play but is always muted by default. We have to manually unmute the player in order to listen to the sound. Same thing works well on web and the audio starts to play and is audible(is unmuted by default). But in mobile devices on first time load the player opens the songs in mute mode.

import React, { Component } from 'react';
import ReactJWPlayer from 'react-jw-player';

class Audio extends Component {

    constructor(props) {
        super(props);
    }

    shouldComponentUpdate() {
    	return false;
    }

    render() {
    	return <ReactJWPlayer
    			customProps={{width: 600, height: 40}}
                playerId="music-player"
                licenseKey='key'
                playerScript='scriptfile'
                file={this.props.active.file}
                onReady={this.props.onReady}
                isAutoPlay={true}
                image={this.props.active.image}
              />
    }
}

export {Audio as JWPlayer}

**Comment by danmakenoise** [comment]
Unless things have changed in the recent months, I believe this is due to mobile browser specifications. Almost all of the major browsers will not allow a video to autoplay on a mobile device unless it is muted.

**Comment by danmakenoise** [comment]
Sorry, meant to post more to that:

This is the reason our library automatically does this. You should be able to override the property via the `customProps` prop.

**Comment by danmakenoise** [comment]
My assumption above is that it is the same rules for audio

**Comment by nveen** [comment]
Okay. Thanks for the information. We have removed the autoplay functionality and provided a play button to start the playlist but in this approach, we encountered another issue.

We have provided the option to update the playlist by drag and drop. A user can reposition the songs in the playlist by dragging them and changing the position. Once the order of songs in the playlist is updated we send the updated playlist object to the player to play. But in this case, again the song gets paused. 

Can you please help us and suggest how can we prevent the current song from getting paused once the playlist is updated. Also can you please suggest if the current library of JW player is also available in REDUX.

Thanks a lot in advance for your help and support. Really appreciate it.

**Comment by ellell** [comment]
Pausing of the song likely happens because the component is re-rendered, but it's very hard to give any concrete suggestions on how to handle without knowing how your app is setup.

**Comment by ellell** [comment]
Closing this out, feel free to reopen with more context if you still need help!
